exclude = [
    ".*__pycache__",
    "build/",
    "dist/",
    "docs/",
    "python/tests/",
    "tach.egg-info/",
    "venv/",
]
source_roots = [
    "python",
]
exact = true
disable_logging = false
ignore_type_checking_imports = true
forbid_circular_dependencies = true

[[modules]]
path = "tach"
depends_on = []
strict = true

[[modules]]
path = "tach.__main__"
depends_on = [
    { path = "tach.start", deprecated = false },
]
strict = true

[[modules]]
path = "tach.cache"
depends_on = [
    { path = "tach", deprecated = false },
    { path = "tach.filesystem", deprecated = false },
]
strict = true

[[modules]]
path = "tach.check"
depends_on = [
    { path = "tach.errors", deprecated = false },
    { path = "tach.extension", deprecated = false },
    { path = "tach.filesystem", deprecated = false },
    { path = "tach.parsing", deprecated = false },
]
strict = true

[[modules]]
path = "tach.check_external"
depends_on = [
    { path = "tach.extension", deprecated = false },
    { path = "tach.utils", deprecated = false },
]
strict = false

[[modules]]
path = "tach.cli"
depends_on = [
    { path = "tach", deprecated = false },
    { path = "tach.cache", deprecated = false },
    { path = "tach.check", deprecated = false },
    { path = "tach.check_external", deprecated = false },
    { path = "tach.colors", deprecated = false },
    { path = "tach.constants", deprecated = false },
    { path = "tach.core", deprecated = false },
    { path = "tach.errors", deprecated = false },
    { path = "tach.extension", deprecated = false },
    { path = "tach.filesystem", deprecated = false },
    { path = "tach.logging", deprecated = false },
    { path = "tach.mod", deprecated = false },
    { path = "tach.parsing", deprecated = false },
    { path = "tach.report", deprecated = false },
    { path = "tach.show", deprecated = false },
    { path = "tach.sync", deprecated = false },
    { path = "tach.test", deprecated = false },
    { path = "tach.utils", deprecated = false },
]
strict = true

[[modules]]
path = "tach.colors"
depends_on = []
strict = true

[[modules]]
path = "tach.constants"
depends_on = []
strict = true

[[modules]]
path = "tach.core"
depends_on = [
    { path = "tach.constants", deprecated = false },
]
strict = true

[[modules]]
path = "tach.errors"
depends_on = []
strict = true

[[modules]]
path = "tach.extension"
depends_on = []
strict = false

[[modules]]
path = "tach.filesystem"
depends_on = [
    { path = "tach.colors", deprecated = false },
    { path = "tach.constants", deprecated = false },
    { path = "tach.core", deprecated = false },
    { path = "tach.errors", deprecated = false },
    { path = "tach.hooks", deprecated = false },
]
strict = true

[[modules]]
path = "tach.filesystem.git_ops"
depends_on = [
    { path = "tach.errors", deprecated = false },
]
strict = true

[[modules]]
path = "tach.hooks"
depends_on = [
    { path = "tach.constants", deprecated = false },
]
strict = true

[[modules]]
path = "tach.interactive"
depends_on = [
    { path = "tach.errors", deprecated = false },
    { path = "tach.filesystem", deprecated = false },
]
strict = true

[[modules]]
path = "tach.logging"
depends_on = [
    { path = "tach", deprecated = false },
    { path = "tach.cache", deprecated = false },
    { path = "tach.parsing", deprecated = false },
]
strict = true

[[modules]]
path = "tach.mod"
depends_on = [
    { path = "tach.colors", deprecated = false },
    { path = "tach.constants", deprecated = false },
    { path = "tach.errors", deprecated = false },
    { path = "tach.filesystem", deprecated = false },
    { path = "tach.interactive", deprecated = false },
    { path = "tach.parsing", deprecated = false },
]
strict = true

[[modules]]
path = "tach.parsing"
depends_on = [
    { path = "tach.constants", deprecated = false },
    { path = "tach.core", deprecated = false },
    { path = "tach.errors", deprecated = false },
    { path = "tach.extension", deprecated = false },
    { path = "tach.filesystem", deprecated = false },
]
strict = true

[[modules]]
path = "tach.report"
depends_on = [
    { path = "tach.colors", deprecated = false },
    { path = "tach.errors", deprecated = false },
    { path = "tach.extension", deprecated = false },
    { path = "tach.filesystem", deprecated = false },
    { path = "tach.utils", deprecated = false },
]
strict = true

[[modules]]
path = "tach.show"
depends_on = []
strict = true

[[modules]]
path = "tach.start"
depends_on = [
    { path = "tach.cli", deprecated = false },
]
strict = true

[[modules]]
path = "tach.sync"
depends_on = [
    { path = "tach.check", deprecated = false },
    { path = "tach.core", deprecated = false },
    { path = "tach.errors", deprecated = false },
    { path = "tach.filesystem", deprecated = false },
    { path = "tach.parsing", deprecated = false },
]
strict = true

[[modules]]
path = "tach.test"
depends_on = [
    { path = "tach.errors", deprecated = false },
    { path = "tach.extension", deprecated = false },
    { path = "tach.filesystem", deprecated = false },
    { path = "tach.filesystem.git_ops", deprecated = false },
    { path = "tach.parsing", deprecated = false },
]
strict = true

[[modules]]
path = "tach.utils"
depends_on = []
strict = false

[cache]
backend = "disk"
file_dependencies = [
    "python/tests/**",
    "src/*.rs",
]
env_dependencies = []

[external]
exclude = [
    "pytest",
]
